name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Test
      run: make test
    - name: Test Coverage
      run: |
        go test -cover ./... | grep 100.0% || \
          echo Coverage decreased! > /dev/stderr
    - name: Lint
      run: make lint
