name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: Test
      run: make test
    - name: Test Coverage
      run: |
        go test -cover ./... | grep -F 100.0% || {
          go test -cover ./...
          echo Coverage decreased!
          exit 1
        } >&2
    - name: Lint
      run: make lint
